
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-courses-s24-4pm-4
owner: ucsb-cs156-s24
repo_name: proj-courses-s24-4pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ2MDk1NTAw","is_bot":false,"login":"tihdiR","name":"Ridhit Garg"},"headRefName":"RG-GradeJob-NEW","number":39,"title":"Add Admin Job Frontend for Grade Data","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-4/pull/39"},{"author":{"id":"U_kgDOB0-GGg","is_bot":false,"login":"JLowe32","name":""},"headRefName":"Jaren-CourseHistoryFeature","number":38,"title":"Added Improvement Course History Search Feature ","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-4/pull/38"},{"author":{"id":"U_kgDOB0-GGg","is_bot":false,"login":"JLowe32","name":""},"headRefName":"Jaren-TitleUpdate","number":37,"title":"Updated Web Application Title ","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-4/pull/37"},{"author":{"id":"U_kgDOB0-GGg","is_bot":false,"login":"JLowe32","name":""},"headRefName":"Jaren-H2ConsoleOpt","number":36,"title":"H2 Console Option","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-4/pull/36"},{"author":{"id":"U_kgDOBdLvhw","is_bot":false,"login":"andersonlee3","name":""},"headRefName":"al-bug-modal","number":33,"title":"BUG: Modal for Adding Courses on Basic Course Search Page Displays All Schedules","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-4/pull/33"},{"author":{"id":"MDQ6VXNlcjE3MTAzNzkw","is_bot":false,"login":"WinbertZhang","name":"Winbert Zhang"},"headRefName":"Winbert-PSFrontend","number":29,"title":"Add PersonalSections Frontend Delete Button to Table","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-4/pull/29"},{"author":{"id":"MDQ6VXNlcjQ2MDk1NTAw","is_bot":false,"login":"tihdiR","name":"Ridhit Garg"},"headRefName":"RG-RemoveCourses","number":24,"title":"Remove Courses Page Feature","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-4/pull/24"}]
