
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-courses-s24-4pm-4
owner: ucsb-cs156-s24
repo_name: proj-courses-s24-4pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ2MDk1NTAw","is_bot":false,"login":"tihdiR","name":"Ridhit Garg"},"headRefName":"RG-CourseBug","number":43,"title":"Course Search History Displays in Correct Order","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-4/pull/43"},{"author":{"id":"MDQ6VXNlcjMyNDAyOTk3","is_bot":false,"login":"andrew344c","name":"Andrew"},"headRefName":"Andrew-CourseGradeDist-AddToDetails","number":42,"title":"Added Course Grade Distribution Table to Course Details Page","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-4/pull/42"}]
