
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-courses-s24-4pm-4
owner: ucsb-cs156-s24
repo_name: proj-courses-s24-4pm-4
pull_requests: [{"author":{"id":"U_kgDOB0-GGg","is_bot":false,"login":"JLowe32","name":""},"headRefName":"Jaren-UpdateQuarterMenu","number":27,"title":"Make DefautQtr the EndQtr","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-4/pull/27"},{"author":{"id":"MDQ6VXNlcjQ2MDk1NTAw","is_bot":false,"login":"tihdiR","name":""},"headRefName":"RG-RemoveCourses","number":24,"title":"Remove Courses Page Feature","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-4/pull/24"},{"author":{"id":"MDQ6VXNlcjMyNDAyOTk3","is_bot":false,"login":"andrew344c","name":"Andrew"},"headRefName":"Andrew-CourseGradeDist-Table","number":23,"title":"Create Simple Course Grade Distribution Table Component and Testcases","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-4/pull/23"}]
