
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-courses-s24-4pm-4
owner: ucsb-cs156-s24
repo_name: proj-courses-s24-4pm-4
pull_requests: [{"author":{"id":"U_kgDOB0-GGg","is_bot":false,"login":"JLowe32","name":""},"headRefName":"Jaren-H2ConsoleOpt","number":36,"title":"H2 Console Option","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-4/pull/36"},{"author":{"id":"U_kgDOBdLvhw","is_bot":false,"login":"andersonlee3","name":""},"headRefName":"al-bug-modal","number":33,"title":"BUG: Modal for Adding Courses on Basic Course Search Page Displays All Schedules","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-4/pull/33"},{"author":{"id":"U_kgDOB0-GGg","is_bot":false,"login":"JLowe32","name":""},"headRefName":"Jaren-H2ConsoleOption","number":32,"title":"H2 Console Option","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-4/pull/32"},{"author":{"id":"MDQ6VXNlcjE3MTAzNzkw","is_bot":false,"login":"WinbertZhang","name":"Winbert Zhang"},"headRefName":"Winbert-PSFrontend","number":29,"title":"Add PersonalSections Frontend Delete Button to Table","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-4/pull/29"},{"author":{"id":"MDQ6VXNlcjE3MTAzNzkw","is_bot":false,"login":"WinbertZhang","name":"Winbert Zhang"},"headRefName":"Winbert-PSBackendDelete","number":28,"title":"Add PersonalSections Controller Delete and Tests","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-4/pull/28"},{"author":{"id":"MDQ6VXNlcjQ2MDk1NTAw","is_bot":false,"login":"tihdiR","name":""},"headRefName":"RG-RemoveCourses","number":24,"title":"Remove Courses Page Feature","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-4/pull/24"}]
